name: test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v*
    paths-ignore:
      - '**/README.md'
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "::set-output name=version::$(cat .nvmrc)"
        id: nvmrc

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvmrc.outputs.version }}'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
